#!/usr/bin/env bash
#
# embed_sql.sh — Convert a directory of .sql migration files into a C source
# file containing a compiled db_migration_t array.
#
# Usage: embed_sql.sh <migrations_dir> [array_name]
#
# Output goes to stdout. Redirect to a .c file in your build:
#
#   tools/embed_sql.sh migrations/ > src/migrations_compiled.c
#
# Or as a Makefile rule:
#
#   src/migrations_compiled.c: $(wildcard migrations/*.sql)
#       $(CUTILS_DIR)/tools/embed_sql.sh migrations/ app_migrations > $@

set -euo pipefail

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <migrations_dir> [array_name]" >&2
    exit 1
fi

migrations_dir="$1"
array_name="${2:-app_migrations}"

if [[ ! -d "$migrations_dir" ]]; then
    echo "Error: directory '$migrations_dir' does not exist" >&2
    exit 1
fi

# Collect .sql files in lexical order
mapfile -t sql_files < <(find "$migrations_dir" -maxdepth 1 -name '*.sql' -printf '%f\n' | sort)

if [[ ${#sql_files[@]} -eq 0 ]]; then
    echo "Warning: no .sql files found in '$migrations_dir'" >&2
fi

cat <<HEADER
/* Auto-generated by embed_sql.sh — do not edit */
#include <cutils/db.h>

const db_migration_t ${array_name}[] = {
HEADER

for file in "${sql_files[@]}"; do
    filepath="$migrations_dir/$file"
    printf '    {\n'
    printf '        "%s",\n' "$file"
    printf '        '

    # Read file content, escape backslashes, double quotes, and newlines,
    # then emit as concatenated C string literals (one per line)
    first=1
    while IFS= read -r line || [[ -n "$line" ]]; do
        # Escape backslashes first, then double quotes
        escaped="${line//\\/\\\\}"
        escaped="${escaped//\"/\\\"}"
        if [[ $first -eq 1 ]]; then
            printf '"%s\\n"\n' "$escaped"
            first=0
        else
            printf '        "%s\\n"\n' "$escaped"
        fi
    done < "$filepath"

    printf '    },\n'
done

cat <<FOOTER
    { NULL, NULL }
};
FOOTER
